version: '3.7'

services:
  product_service:
    build: ./product-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./product-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:Pa55W0rD@product_db:5432/ecommerce_db
  product_db:
    image: postgres:12.1
    volumes:
      - postgres_data_product:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa55W0rD
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5432:5432
volumes:
  postgres_data_product: